# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: '#about'
    weight: 1
  - name: Experience
    url: '#experience'
    weight: 2
  - name: Certifications
    url: '#certifications'
    weight: 3
  - name: Blog
    url: '#blog'
    weight: 4
  - name: Projects
    url: '#projects'
    weight: 5
  - name: Contact
    url: '#contact'
    weight: 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
